export enum ResourceType {
    TEXTFIELD = "granite/ui/components/coral/foundation/form/textfield",
    CONTAINER = "granite/ui/components/coral/foundation/container",
    CHECKBOX = "granite/ui/components/coral/foundation/form/checkbox",
    PATH_FIELD = "granite/ui/components/coral/foundation/form/pathfield",
    DATE_PICKER = "granite/ui/components/coral/foundation/form/datepicker",
    FILE_UPLOAD = "cq/gui/components/authoring/dialog/fileupload",
    NUMBER_FIELD = "granite/ui/components/coral/foundation/form/numberfield",
    PATH_BROWSER = "granite/ui/components/coral/foundation/form/pathbrowser",
    TEXTAREA = "granite/ui/components/coral/foundation/form/textarea",
    SELECT = "granite/ui/components/coral/foundation/form/select",
    FIELD = "granite/ui/components/coral/foundation/form/field",
    MULTIFIELD = "granite/ui/components/coral/foundation/form/multifield",
    RADIO_GROUP = "granite/ui/components/coral/foundation/form/radiogroup",
    RICH_TEXT = "cq/gui/components/authoring/dialog/richtext",
    ACCORDION = "/libs/granite/ui/components/coral/foundation/accordion",
    ACTION_BAR = "/libs/granite/ui/components/coral/foundation/actionbar",
    ALERT = "/libs/granite/ui/components/coral/foundation/alert",
    ANCHOR_BUTTON = "/libs/granite/ui/components/coral/foundation/anchorbutton",
    BUTTON = "/libs/granite/ui/components/coral/foundation/button",
    COLUMN_VIEW = "/libs/granite/ui/components/coral/foundation/columnview",
    CONTSYS = "/libs/granite/ui/components/coral/foundation/contsys",
    CYCLE_BUTTON = "/libs/granite/ui/components/coral/foundation/cyclebutton",
    DIALOG = "/libs/granite/ui/components/coral/foundation/dialog",
    FIXED_COLUMNS = "/libs/granite/ui/components/coral/foundation/fixedcolumns",
    HEADING = "/libs/granite/ui/components/coral/foundation/heading",
    HYPERLINK = "/libs/granite/ui/components/coral/foundation/hyperlink",
    INCLUDE = "/libs/granite/ui/components/coral/foundation/include",
    INCLUDE_CLIENTLIBS = "/libs/granite/ui/components/coral/foundation/includeclientlibs",
    LIST = "/libs/granite/ui/components/coral/foundation/list",
    MASONRY = "/libs/granite/ui/components/coral/foundation/masonry",
    META = "/libs/granite/ui/components/coral/foundation/meta",
    PAGE = "/libs/granite/ui/components/coral/foundation/page",
    PANEL = "/libs/granite/ui/components/coral/foundation/panel",
    PICKER = "/libs/granite/ui/components/coral/foundation/picker",
    POPOVER = "/libs/granite/ui/components/coral/foundation/popover",
    PULLDOWN = "/libs/granite/ui/components/coral/foundation/pulldown",
    TABLE = "/libs/granite/ui/components/coral/foundation/table",
    TABS = "/libs/granite/ui/components/coral/foundation/tabs",
    TEXT = "/libs/granite/ui/components/coral/foundation/text",
    WELL = "/libs/granite/ui/components/coral/foundation/well",
    WIZARD = "/libs/granite/ui/components/coral/foundation/wizard",
    ADMIN_CONTENT_CHECKER = "/libs/granite/ui/components/coral/foundation/admin/contentchecker",
    AUTHORIZABLE_PREFERENCES_FORM = "/libs/granite/ui/components/coral/foundation/authorizable/preferencesform",
    COLLECTION_ACTION = "/libs/granite/ui/components/coral/foundation/collection/action",
    COLLECTION_ACTION_LINK = "/libs/granite/ui/components/coral/foundation/collection/actionlink",
    ACTION_FIELD = "/libs/granite/ui/components/coral/foundation/form/actionfield",
    FORM_COLOR_FIELD = "/libs/granite/ui/components/coral/foundation/form/colorfield",
    FORM_FIELD = "/libs/granite/ui/components/coral/foundation/form/field",
    FORM_FIELD_SET = "/libs/granite/ui/components/coral/foundation/form/fieldset",
    FORM_NESTED_CHECKBOX_LIST = "/libs/granite/ui/components/coral/foundation/form/nestedcheckboxlist",
    FORM_RESPONSES_OPEN_PROMPT = "/libs/granite/ui/components/coral/foundation/form/responses/openprompt",
    FORM_RESPONSES_REDIRECT = "/libs/granite/ui/components/coral/foundation/form/responses/redirect",
    FORM_RESPONSES_RELOAD = "/libs/granite/ui/components/coral/foundation/form/responses/reload",
    MODE_FORM = "/libs/granite/ui/components/coral/foundation/mode/form",
    MODE_SWITCHER = "/libs/granite/ui/components/coral/foundation/mode/switcher",
    PAGE_BODY = "/libs/granite/ui/components/coral/foundation/page/body",
    PAGE_FAV_ICON = "/libs/granite/ui/components/coral/foundation/page/favicon",
    PAGE_FRAGMENT = "/libs/granite/ui/components/coral/foundation/page/fragment",
    PANEL_RAIL_PANEL = "/libs/granite/ui/components/coral/foundation/panel/railpanel",
    RENDER_CONDITIONS_FEATURE = "/libs/granite/ui/components/coral/foundation/renderconditions/feature",
    RENDER_CONDITIONS_PRIVILEGE = "/libs/granite/ui/components/coral/foundation/renderconditions/privilege",
    RENDER_CONDITIONS_SIMPLE = "/libs/granite/ui/components/coral/foundation/renderconditions/simple",
    WIZARD_LAZY_CONTAINER = "/libs/granite/ui/components/coral/foundation/wizard/lazycontainer",
    WIZARD_LAZY_STEP = "/libs/granite/ui/components/coral/foundation/wizard/lazystep",
}

export type Prop = {
    field: string;
    value: any;
};

export type Attributes = Record<string, string>;
